/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package mcontrol */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "p0.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "p1.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "p2.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// create_serial_port creates a serial session for RS232 or RS485. This instance maintains only one connection.
// Returns: A JSON string. The caller must release it with free_string after use.
//
extern __declspec(dllexport) char* create_serial_port(char* portName, int baudRate);

// create_pcan_port creates a PCAN session. This instance maintains only one connection.
// Returns: A JSON string. The caller must release it with free_string after use.
//
extern __declspec(dllexport) char* create_pcan_port(char* usbBus, char* rate);

// create_cxcan_port creates a CxCAN session. This instance maintains only one connection.
// Returns: A JSON string. The caller must release it with free_string after use.
//
extern __declspec(dllexport) char* create_cxcan_port(char* canPort, char* rate);

// close_session closes the current session.
//
extern __declspec(dllexport) char* close_session(void);

// free_string releases strings returned by JSON APIs.
//
extern __declspec(dllexport) void free_string(char* p);

// read_int reads an integer value (supports int8, int16, int32, and related types).
//
extern __declspec(dllexport) char* read_int(int station, int address, char* dataType);

// write_int writes an integer value (supports int8, int16, int32, and related types).
//
extern __declspec(dllexport) char* write_int(int station, int address, char* dataType, int32_t value);

// read_string reads a string value.
//
extern __declspec(dllexport) char* read_string(int station, int address);

// write_string writes a string value.
//
extern __declspec(dllexport) char* write_string(int station, int address, char* data);

// list_ports gets the list of available ports.
//
extern __declspec(dllexport) char* list_ports(char* typeStr);

// get_last_error_msg gets the most recent error message.
//
extern __declspec(dllexport) int get_last_error_msg(char* buffer, int bufferSize);

// clear_last_error clears the most recent error message.
//
extern __declspec(dllexport) void clear_last_error(void);
extern __declspec(dllexport) char* read_encoder_ppr(int station);
extern __declspec(dllexport) char* read_pos_actual(int station);
extern __declspec(dllexport) char* read_speed_real(int station);
extern __declspec(dllexport) char* read_torque(int station);
extern __declspec(dllexport) char* set_operation_mode(int station, int mode);
extern __declspec(dllexport) char* set_controlword(int station, int controlword);
extern __declspec(dllexport) char* set_target_position(int station, int32_t position);
extern __declspec(dllexport) char* set_position_p(int station, int32_t p);
extern __declspec(dllexport) char* set_speed_p(int station, int32_t p);
extern __declspec(dllexport) char* set_speed_i(int station, int32_t i);
extern __declspec(dllexport) char* drive_reboot(int station);
extern __declspec(dllexport) char* read_torque_coefficient(int station);
extern __declspec(dllexport) char* set_stiffness(int station, int32_t stiffness);
extern __declspec(dllexport) char* set_damping(int station, int32_t damping);
extern __declspec(dllexport) char* read_damping(int station);
extern __declspec(dllexport) char* read_stiffness(int station);
extern __declspec(dllexport) char* read_operation_mode_buffer(int station);
extern __declspec(dllexport) char* read_statusword(int station);
extern __declspec(dllexport) char* read_iq(int station);
extern __declspec(dllexport) char* set_cmd_q_max(int station, int32_t qMax);
extern __declspec(dllexport) char* read_max_current(int station);
extern __declspec(dllexport) char* set_max_torque(int station, int32_t maxTorque);
extern __declspec(dllexport) char* set_profile_speed(int station, int32_t speed);
extern __declspec(dllexport) char* set_profile_acc(int station, int32_t acc);
extern __declspec(dllexport) char* set_profile_dec(int station, int32_t dec);

#ifdef __cplusplus
}
#endif
